### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by DuBarTech** [longhoang3108/longth18#1]
**thx**

**Comment by DuBarTech** [comment]
no support? LOL I knew you just copied someone else work and you cant even fix yourself kiddo !

**Comment by janya171** [comment]
> File "D:\code\view-tiktok-main\main.py", line 167, in with open('devices.txt', 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'devices.txt'
> 
> **thx**
Bro I know you frustrating but use this to fix it:
**D:\\code\\view-tiktok-main\\main.py**
and add in all 3 data calling path this "\\" instead of your "\"

thats it.

**Comment by DuBarTech** [comment]
> > File "D:\code\view-tiktok-main\main.py", line 167, in with open('devices.txt', 'r') as f: FileNotFoundError: [Errno 2] No such file or directory: 'devices.txt'
> > **thx**
> > Bro I know you frustrating but use this to fix it:
> > **D:\code\view-tiktok-main\main.py**
> > and add in all 3 data calling path this "\" instead of your ""
> 
> thats it.

OMG thank you!

**Comment by DuBarTech** [comment]
kgug
